unique_ids:
  forms:
    Form1: 7IOPV624SB3TZHD4MDA5KOD4URH3WT3A
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: OVBP3LROETWUH5XS4JBVEEQ4IB5M6FPI
    theme.css: YYZC7GNOMX5G463DY6ADO54SWPAISX3I
  scripts: {}
